{
   pkgs,
   ...
}: {
home.packages = with pkgs; [
       fuzzel
       waybar
       superfile
       swaylock
       overskride
       zed-editor
       opencode
       awww
        swaynotificationcenter
        brightnessctl
        power-profiles-daemon
         python3
         zip
         unzip
         kdePackages.okular
         kdePackages.calligra
         jdk
         steam-run
         quickshell
         gimp
         ripgrep
         ghostty
         pavucontrol
         nixd
       ];
}
